### ISSUE TITLE
'BNCLinkCache.h' file not found

### ISSUE THREAD

**Issue by jay-zhu** [BranchMetrics/Branch-iOS-SDK#102]
I upgrade sdk to v0.7.1, but when i complied, it got error 'BNCLinkCache.h' file not found. I m not using cocoa pod

**Comment by shortstuffsushi** [comment]
Hi @jay-zhu. Sounds like we compiled the framework incorrectly. Where are you getting your code from if not Cocoapods? I'll update the location with a fixed version shortly.

**Comment by jay-zhu** [comment]
hi @shortstuffsushi, from the document.https://dev.branch.io/references/ios_sdk/#installation
https://s3-us-west-1.amazonaws.com/branchhost/Branch-iOS-SDK.zip

**Comment by shortstuffsushi** [comment]
Perfect, thanks! Will update shortly :smile:

**Comment by shortstuffsushi** [comment]
The files have been updated, please let me know if this works for you.

**Comment by jay-zhu** [comment]
Yes, it works now. Thanks.

**Comment by shortstuffsushi** [comment]
No problem, sorry about that. Feel free to let us know if you come across any additional issues.
