### ISSUE TITLE
problem in 0.7.4 release

### ISSUE THREAD

**Issue by neil477** [BranchMetrics/Branch-iOS-SDK#105]
I get Branch-SDK/Branch-SDK/BNCServerInterface.h not found when I try to build with Branch 0.7.4 which I installed via cocoapods

**Comment by shortstuffsushi** [comment]
@neil477 I think you're referring to `0.7.2`, but you're right, I added the wrong header to the podspec. Will be updating within the next 20 minutes.

**Comment by shortstuffsushi** [comment]
@neil477 this should be fixed with the latest version, `0.7.3`. Please let me know if this works for you.

**Comment by shortstuffsushi** [comment]
Hi @neil477 -- I'm gonna close this for now since I believe this is fixed. If you're still seeing problems, please let me know.
