### ISSUE TITLE
Question about the security issues. 

### ISSUE THREAD

**Issue by microgomi** [BranchMetrics/Branch-iOS-SDK#112]
Hi there, 
We are using the branch SDK for sending data by link and the data of the link is very personal information.
So I have a question, the data is attached to link is secure? 
Or we have to encrypt that data ourselves?

**Comment by aaustin** [comment]
@microgomi - great question! It's very secure, but for extra safety, we recommend that you hash any personal information before you insert it into the Branch link. Hope this helps!

**Comment by microgomi** [comment]
Thank you :-) I will do. .
