### ISSUE TITLE
Referral

### ISSUE THREAD

**Issue by Alkalouti** [BranchMetrics/Branch-iOS-SDK#120]
Hi All,
how to add referral value at getBranchActivityItemWithParams

**Comment by shortstuffsushi** [comment]
Hi @Alkalouti. I'm not sure what you're referring to; are you looking to use a referral url? If so, just pass in the [`BRANCH_FEATURE_TAG_REFERRAL`](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.h#L27) constant to the [`getBranchActivityItemWithParams:feature:`](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/master/Branch-SDK/Branch-SDK/Branch.h#L99)

**Comment by Alkalouti** [comment]
Hi @shortstuffsushi ,
Yes i want to use referral url in UIActivityViewController,

i add this code into my app:

NSString *shareString = @"Super amazing thing I want to share!";
UIImage *amazingImage = [UIImage imageNamed:@"Super-Amazing-Image.png"];

NSMutableDictionary *params = [[NSMutableDictionary alloc] init];

[params setObject:@"Joe" forKey:@"user"];
[params setObject:@"https://s3-us-west-1.amazonaws.com/myapp/joes_pic.jpg" forKey:@"profile_pic"];
[params setObject:@"Joe likes long walks on the beach..." forKey:@"description"];

// Customize the display of the link
[params setObject:@"Joe's My App Referral" forKey:@"$og_title"];
[params setObject:@"https://s3-us-west-1.amazonaws.com/myapp/joes_pic.jpg" forKey:@"$og_image_url"];
[params setObject:@"Join Joe in My App - it's awesome" forKey:@"$og_description"];

// Customize the redirect performance
[params setObject:@"http://myapp.com/desktop_splash" forKey:@"$desktop_url"];

NSArray *tags = @[@"tag1", @"tag2"];
NSString *feature = @"invite";//just add here (BRANCH_FEATURE_TAG_REFERRAL) ??
NSString *stage = @"2";

// Branch UIActivityItemProvider
UIActivityItemProvider *itemProvider = [Branch getBranchActivityItemWithParams:params andFeature:feature andStage:stage andTags:tags];

Thanks for your replay.

**Comment by shortstuffsushi** [comment]
Precisely. Give that a shot, and let us know if that's what you're looking for.

**Comment by Alkalouti** [comment]
Thanks @salomeshah  I'll reply to you soon i'm out of the office right now

**Comment by Alkalouti** [comment]
Hi @salomeshah it's work fine but i need to pass User ID for referral to connect it with my users id

**Comment by Alkalouti** [comment]
@salomeshah thanks a lot man, i add  [[Branch getInstance] setIdentity:@"id"]; every things working good.
Thank you again.

**Comment by shortstuffsushi** [comment]
Hey @Alkalouti. Glad it's working for you. Fwiw, you're tagging a random user, not me :laughing: I'm closing this issue for now, if you run into other ones, please feel free to contact us again.
