### ISSUE TITLE
Crash in - (void)setIdentity:(NSString *)userId

### ISSUE THREAD

**Issue by ralonsocf** [BranchMetrics/Branch-iOS-SDK#121]
If user session is not yet initialized when call to setIdentity the app crash trying to create the post dictionary because [BNCPreferenceHelper getDeviceFingerprintID], [BNCPreferenceHelper getSessionID], [BNCPreferenceHelper getIdentityID] return nil values.

**Comment by shortstuffsushi** [comment]
@ralonsocf Hmm, there should be blocks to prevent those requests from going through if that's not initialized, but perhaps it's not correct. Will check and fix for you -- sorry about that.

**Comment by shortstuffsushi** [comment]
Ah, there is a check, but the request bodies are being constructed too early. This will be fixed by an outstanding pull request, which should be in this afternoon I hope.

**Comment by ralonsocf** [comment]
Thanks Graham!

**Comment by mltk96** [comment]
any update about the fix release?

**Comment by shortstuffsushi** [comment]
Sorry for the delay, just waiting on review of #113. Hopefully will have it out by early next week.

**Comment by shortstuffsushi** [comment]
Hi guys, the update has been released! Please give it a shot, and let us know if you run into any problems. Sorry about that :frowning:
