### ISSUE TITLE
Crash Branch.m 1356 -[Branch processNextQueueItem]

### ISSUE THREAD

**Issue by Alkalouti** [BranchMetrics/Branch-iOS-SDK#125]
Hi,
I got this crash on crashlytics many times please advise me about it 

![brach](https://cloud.githubusercontent.com/assets/3541656/8058495/7b1a8348-0ec2-11e5-86e3-5d0f177432cb.png)

**Comment by shortstuffsushi** [comment]
Hi @Alkalouti. I believe this crash was resolved as of `0.7.7`. What version of Branch are you using that you're seeing this on?

**Comment by Alkalouti** [comment]
Hi @shortstuffsushi please advice from where i can know the version number i use Branch.framework I download it from branch website last week

**Comment by shortstuffsushi** [comment]
The version number is available within the `BNCConfig.h` file. However, I don't think this header is currently exposed within the framework (making a note to do so). I think for now it would be best to try updating to a more recent version, as there was a [specific commit](https://github.com/BranchMetrics/Branch-iOS-SDK/commit/f22d05c18806583527f855def1d41be5f1122929) that fixed this issue June 3rd as part of the `0.7.8` release.

**Comment by Alkalouti** [comment]
i check it now i use version 0.7.8

**Comment by shortstuffsushi** [comment]
Are you saying the current version you're using is `0.7.8`, or that you're upgrading?

**Comment by Alkalouti** [comment]
no i use 0.7.8 version

**Comment by shortstuffsushi** [comment]
I'm interpreting that to mean you're currently using the version. However, I'm surprised you would be seeing that issue, as that version was specifically the fix for what you're seeing. Could you please check again and be sure that the version of your app that you're seeing crashes on contains Branch `0.7.8`?

**Comment by Alkalouti** [comment]
ok i already have a version on review, i checked now i have to version on my device one of them 0.7.5 and the other is 0.7.8 i really don't know witch one i use i download now the latest and add it into my app.
thanks a lot.
and if i have the same problem i give a feedback on it thanks @shortstuffsushi

**Comment by shortstuffsushi** [comment]
No problem, sorry for the confusion. If you continue to see this issue in later versions, please reopen the issue.
