### ISSUE TITLE
Clear BNCLinkCache on logout

### ISSUE THREAD

**Issue by erickreutz** [BranchMetrics/Branch-iOS-SDK#138]
Running into a problem where a user logs out and another user then logs in. We go to generate a referral URL for the new user and it returns the referral URL from the BNCLinkCache for the previous user. Is this by design? Should the link cache be cleared when a user logs out?

**Comment by qinweigong** [comment]
@erickreutz Thanks a lot for the feedback! Really appreciate it! We will look into this issue soon.

**Comment by erickreutz** [comment]
@shortstuffsushi killing it! Awesome turn around time guys

**Comment by shortstuffsushi** [comment]
Hi @erickreutz  -- this should be available with `0.9.3` on Cocoapods :+1: Good catch!
