### ISSUE TITLE
initsession is not triggered well @first launch.

### ISSUE THREAD

**Issue by shineall** [BranchMetrics/Branch-iOS-SDK#45]
initsession's RegisterDeeplinkHandler is not triggered well @first launch. after killing app and relaunch, it works again. there is still issue on session init on latest update.

**Comment by aaustin** [comment]
@shineall we literally just realized this was happening right when you posted. I just pushed a fix. Can you sync or pull latest Cocoapod? I'm so sorry!

**Comment by qinweigong** [comment]
@shineall The problem should be completely fixed in our update 0.3.101. Please check it out! Again, sorry for the problem and thanks a lot for your feedback!

**Comment by shineall** [comment]
@aaustin @qinweigong  thank you for fast response & quick update !
