### ISSUE TITLE
CocoaPod doesn't compile

### ISSUE THREAD

**Issue by AdamPro13** [BranchMetrics/Branch-iOS-SDK#47]
I just updated to `0.4.0` and it doesn't compile with error message: `'BranchActivityItemProvider.h' file not found`

**Comment by qinweigong** [comment]
Hi @AdamPro13 , thanks a lot for reaching out and letting us know! Sorry about the miss! We just added the new header file to our podspec file and updated with a newer version 0.4.1. Please check it out!

**Comment by AdamPro13** [comment]
Thanks, it's working now.

**Comment by qinweigong** [comment]
Cool! Thanks for your support for Branch! Happy linking! :-)
