### ISSUE TITLE
third party keyboard make crash.

### ISSUE THREAD

**Issue by shineall** [BranchMetrics/Branch-iOS-SDK#55]
I tired to use TouchPal (one of popular new keyboard app) as my keyboard. 
when I click textfield to trigger keyboard. It crashed app.

+ (BOOL)isSimulator {
    UIDevice *currentDevice = [UIDevice currentDevice];
    return [currentDevice.model rangeOfString:@"Simulator"].location != NSNotFound;
}
make crash in BNCSystemObserver.

Default iOS keyboard works fine. I think this can affect many cases when user use another keyboard.

**Comment by shortstuffsushi** [comment]
Hi @shineall. I just looked into this a bit, and am having a hard time reproducing the issue you're seeing. I'm assuming you're using iOS 8, and are running the app on a device. Could you clarify a few additional items about where you're seeing this issue?

- Which method is triggering the call to `isSimulator`?
- Are you seeing this crash in the Branch TestBed app or in your own app?
- Do you have Branch debugging enabled, and have you connected via the long press?

**Comment by qinweigong** [comment]
Hi @shineall 

We tested Coffee Meets Bagel with TouchPal, and did reproduced the crash!
However, reading through the crash report log, we couldn't find anything related to our SDK. Could you point us to where you trace back to the isSimulator function? I'd greatly appreciate it if you could provide some clue!

Have a nice weekend!

**Comment by shineall** [comment]
Thank you for quick response.
[Situation]
- iOS 8.1.2 (i am not sure this is related to. just share dev env)
- I did not turn on Debug mode of Branch.
- When I touch with finger(for 1 sec) on UITextfield  , this function was triggered in UIViewController + BNCDebugger (category) 

- (void)bnc_addGesterRecognizer:(SEL)action {
    BNCLongPress = [[UILongPressGestureRecognizer alloc] initWithTarget:self action:action];
    BNCLongPress.cancelsTouchesInView = NO;
    BNCLongPress.minimumPressDuration = BNCDebugTriggerDuration;
    if (![BNCSystemObserver isSimulator]) {
        BNCLongPress.numberOfTouchesRequired = BNCDebugTriggerFingers;
    } else {
        BNCLongPress.numberOfTouchesRequired = BNCDebugTriggerFingersSimulator;
    }
    [self.view addGestureRecognizer:BNCLongPress];
}

[Crash point] 
    if (![BNCSystemObserver isSimulator])  have crashed on device (not simulator)

**Comment by qinweigong** [comment]
Oh, this might be related to a bug we found and fixed a while back. Please update to our latest iOS SDK v0.4.4

Please let me know if the problem is gone or not after the update.

Thanks so much for the feedback!

**Comment by shineall** [comment]
@qinweigong Thank you! 
I gonna test it with latest version and let you know.

**Comment by shineall** [comment]
@qinweigong Thank you. I confirmed no crash in v0.4.4.

**Comment by qinweigong** [comment]
@shineall Cool!
