### ISSUE TITLE
SDK breaks iOS 6

### ISSUE THREAD

**Issue by scosman** [BranchMetrics/Branch-iOS-SDK#58]
Your using several constants not defined on iOS 6, causing a crash on startup.

 - UIActivityTypeAddToReadingList
 - UIActivityTypeAirDrop
 - UIActivityTypePostToFlickr
 - UIActivityTypePostToTencentWeibo
 - UIActivityTypePostToVimeo

**Comment by qinweigong** [comment]
Hi @scosman ,

I am so sorry about the issue and thank a lot for reaching out to us!

We will get this fixed ASAP.

Thanks,

Qinwei

**Comment by scosman** [comment]
No worries: easy workaround for anyone else encountering this: just define them in a header.

**Comment by shortstuffsushi** [comment]
This should be fixed by #59, could you verify?

**Comment by scosman** [comment]
already shipped with workaround. I'll try for next update.

**Comment by shortstuffsushi** [comment]
Cool, glad you got around it. I'm going to close this for now -- if you still see any issue popping up with the latest, please reopen :smile:
