### ISSUE TITLE
Question - Does getShortURLWithParams generate a unique URL every time?

### ISSUE THREAD

**Issue by JALsnipe** [BranchMetrics/Branch-iOS-SDK#64]
I wasn't sure where to post this question, so I figured GitHub would be ok.

Does `getShortURLWithParams` generate a unique URL every time it is called?  Say I generate a url with `getShortURLWithParams:andChannel:andFeature:andStage:andCallback`, and then I immediately call the method again with the same exact params, tags, channel, feature, and stage.  What is the expected behavior?  Should a unique URL be generated and a new row be added under "Export" on the dashboard?

Thanks, and let me know if there is a more appropriate place to ask this question.

**Comment by qinweigong** [comment]
Hi @JALsnipe,

Thanks for reaching out with this great question! It's fine to ask questions here.

Actually, we have a cache for URLs built in the SDK. If within a session you try to call getShortURL (all overloaded variants) repeatedly with the exact same set of parameter values, it will just return the url previously generated and stored in the cache!

The purpose is to save server side API roundtrip calls. If you call getShortURL with different params, you will get a different url then. 
Also, the URL cache only lives with the current session. Once a new session starts, the cache will build from scratch again.

Hope this helps. Let me know if you have any further questions or suggestions.

Thanks,

Qinwei

**Comment by JALsnipe** [comment]
Thanks for your detailed answer, this is exactly the answer I needed!
