### ISSUE TITLE
setIdentity not updating User ID

### ISSUE THREAD

**Issue by kenleezle** [BranchMetrics/Branch-iOS-SDK#71]
I am getting mixed results using setIdentity:

* When I run a beta build in XCode, the call to setIdentity works only after a fresh install, subsequent calls do not update the identity
* When i run the same build from TestFlight, the call to setIdentity never has any effect.

I am observing the effect using the dashboard at branch.io

**Comment by shortstuffsushi** [comment]
Hi @kenleezle, I have a couple of questions for you to help us review a bit further.

* Are you updating the identity to the same value each time, or do you set it to a unique identity each time?
* Are you seeing no callback called, or is it called with an error (or with the same result, regardless of the value you provided)?

**Comment by kenleezle** [comment]
1. I am updating the identity to a different value each time, and observing the influencers in the dashboard to see if the User Id changes.
2. I do not see a callback parameter in the setIdentity method signature. I am not using any callback.

**Comment by shortstuffsushi** [comment]
The method with a callback is listed [here](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/e1477321ff4e172ebe35888dd73c454bb202f592/Branch-SDK/Branch-SDK/Branch.h#L105), try giving that a shot and let us know if you do see a successful response, or an error.

With your the identity value, we do have a constraint that it be less than 64 characters; is your value in that range?

**Comment by shortstuffsushi** [comment]
Also, which SDK version are you using? Should have gotten that out of the way right away.

**Comment by kenleezle** [comment]
@shortstuffsushi close this issue, what is happening is that from beta to testflight my branch id is changing, which is fine.... it was unexpected but not an issue per say.

**Comment by shortstuffsushi** [comment]
OK, let us know if we can do anything else to help :smile:

**Comment by qinweigong** [comment]
Hi @kenleezle 

Just want to follow up with a suggestion: for best accuracy, you may want to have setIdentity always paired with a [branch logout]; call before calling it again. Please ignore it if you are already doing so.

**Comment by kenleezle** [comment]
thanks @qinweigong  i'll do that
