### ISSUE TITLE
sdk v0.6.0 crashes

### ISSUE THREAD

**Issue by mltk96** [BranchMetrics/Branch-iOS-SDK#81]
after updating the SDK to v0.6.0 it crashing inside updateAllRequestsInQueue, on the next action:
                [request.postData setValue:[BNCPreferenceHelper getSessionID] forKey:SESSION_ID];
with the next crash:
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<__NSDictionaryI 0x1740f4a00> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key session_id.'
*** First throw call stack:

**Comment by shortstuffsushi** [comment]
Hi @mltk96, really sorry about that. This is a bug on our part; trying to call `setValue:forKey` on an immutable dictionary. I've pull requested the fix for this, and should have it out to your for use shortly.

**Comment by shortstuffsushi** [comment]
Hi again @mltk96. The fix for this issue should be available in 0.6.1. Please let us know if you run into any additional issues.
