### ISSUE TITLE
Missing file on v0.6.3 installation through Cocoapods

### ISSUE THREAD

**Issue by e7mac** [BranchMetrics/Branch-iOS-SDK#98]
When the Branch version moved from 0.6.2 to 0.6.3 while running pod update, it stopped compiling, saying `BNCLinkCache.h` not found in the `Branch.h` file.

**Comment by shortstuffsushi** [comment]
Hi @e7mac, sorry to hear you're having trouble! Are you using the `HEAD` of the repository by chance? The change you've mentioned isn't released yet, so I'm surprised you would see that warning.

**Comment by shortstuffsushi** [comment]
@e7mac I've committed the update to `master` that should fix that for you. Sorry about that.

Just as a word of caution, I don't think running against `HEAD` of our repo (or any really) is in your best interest. `HEAD` includes changes that aren't necessarily stable, and have subsequently not been released for public consumption yet.

Typically, you'd only want to use `HEAD` in a scenario where the Pod itself wasn't being released / updated any more, and there were fixes / feature you required that weren't available in a tag. Are there any features that you were specifically looking for that aren't available view the released Pod?

**Comment by e7mac** [comment]
@shortstuffsushi thanks for the fix! I started pointing my Pods to the GitHub repo because the official cocoapods was still pointing to v0.5.x and there were issues with the `branch_key` and I couldn't figure out how to point to a particular release if I was specifying the `:git` in my Podfile.  But now I'll start pointing to a particular commit instead. Thanks for the help!

**Comment by shortstuffsushi** [comment]
Hey @e7mac, just to clarify, I'm not recommending using `:git` or a particular commit, you should use the released version of Branch on the CocoaPods trunk, like `pod 'Branch', '0.7.1'`.
